name: election-analysis
channels:
  - defaults
  - plotly
dependencies:
  - plotly
  - geopandas
  - pandas
  - python[version='>=3.8']
  - jupyterlab
  - matplotlib
  - descartes
  - ipywidgets=7.5
  - python-kaleido
  - psutil
  - dash
